name: Push to docker hub

on: 
    push:
        tags:
            - "*"
    create:
        tags:
            - "*"

jobs:
    push-to-docker-hub:
        name: build and push the latest image to docker hub
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                ref: ${{ github.ref }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.dockerhub_username }}
                password: ${{ secrets.dockerhub_access_token }}

            - name: Get tag
              id: get_tag
              run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: mmohaveri/letsencrypt-ready-nginx:${{ steps.get_tag.outputs.TAG }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
